syntax = "proto3";

message  AnnotationRequest{
  string in_img_path = 1;
  bool process_all_flag = 2;
  string out_img_path = 3;
  string white_img_path = 4;
  string black_img_path=5;
  repeated string in_img_list = 6;
  bool is_preview_flag =7;
}

message AnnotationResponse {
  string job_id = 1;
  int32 percentage = 2;
  string white_img_path = 3;
  string black_img_path = 4;
  string status_message = 6;
  bool completed = 7;
  string error_message = 8;
  string process_type = 9;
  int32 status_code = 10;
}
