# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: annotation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'annotation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61nnotation.proto\"\xb6\x01\n\x11\x41nnotationRequest\x12\x13\n\x0bin_img_path\x18\x01 \x01(\t\x12\x18\n\x10process_all_flag\x18\x02 \x01(\x08\x12\x14\n\x0cout_img_path\x18\x03 \x01(\t\x12\x16\n\x0ewhite_img_path\x18\x04 \x01(\t\x12\x16\n\x0e\x62lack_img_path\x18\x05 \x01(\t\x12\x13\n\x0bin_img_list\x18\x06 \x03(\t\x12\x17\n\x0fis_preview_flag\x18\x07 \x01(\x08\"\xd5\x01\n\x12\x41nnotationResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\npercentage\x18\x02 \x01(\x05\x12\x16\n\x0ewhite_img_path\x18\x03 \x01(\t\x12\x16\n\x0e\x62lack_img_path\x18\x04 \x01(\t\x12\x16\n\x0estatus_message\x18\x06 \x01(\t\x12\x11\n\tcompleted\x18\x07 \x01(\x08\x12\x15\n\rerror_message\x18\x08 \x01(\t\x12\x14\n\x0cprocess_type\x18\t \x01(\t\x12\x13\n\x0bstatus_code\x18\n \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'annotation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANNOTATIONREQUEST']._serialized_start=21
  _globals['_ANNOTATIONREQUEST']._serialized_end=203
  _globals['_ANNOTATIONRESPONSE']._serialized_start=206
  _globals['_ANNOTATIONRESPONSE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
