# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: denoise.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'denoise.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdenoise.proto\"\x9d\x01\n\x10\x41veragingRequest\x12\x13\n\x0bin_img_path\x18\x01 \x01(\t\x12\x18\n\x10process_all_flag\x18\x02 \x01(\x08\x12\x13\n\x0bin_img_list\x18\x03 \x03(\t\x12\x14\n\x0cout_img_path\x18\x04 \x01(\t\x12\x17\n\x0fis_preview_flag\x18\x05 \x01(\x08\x12\x16\n\x0ein_filter_size\x18\x06 \x01(\x05\"\xa5\x01\n\x18GaussianSmoothingRequest\x12\x13\n\x0bin_img_path\x18\x01 \x01(\t\x12\x18\n\x10process_all_flag\x18\x02 \x01(\x08\x12\x13\n\x0bin_img_list\x18\x03 \x03(\t\x12\x14\n\x0cout_img_path\x18\x04 \x01(\t\x12\x17\n\x0fis_preview_flag\x18\x05 \x01(\x08\x12\x16\n\x0ein_filter_size\x18\x06 \x01(\x05\"\xc2\x01\n\x19\x42ilateralFilteringRequest\x12\x13\n\x0bin_img_path\x18\x01 \x01(\t\x12\x18\n\x10process_all_flag\x18\x02 \x01(\x08\x12\x13\n\x0bin_img_list\x18\x03 \x03(\t\x12\x14\n\x0cout_img_path\x18\x04 \x01(\t\x12\x17\n\x0fis_preview_flag\x18\x05 \x01(\x08\x12\x16\n\x0ein_filter_size\x18\x06 \x01(\x05\x12\x1a\n\x12in_variation_range\x18\x07 \x01(\x05\"\xa3\x01\n\x16MedianFilteringRequest\x12\x13\n\x0bin_img_path\x18\x01 \x01(\t\x12\x18\n\x10process_all_flag\x18\x02 \x01(\x08\x12\x13\n\x0bin_img_list\x18\x03 \x03(\t\x12\x14\n\x0cout_img_path\x18\x04 \x01(\t\x12\x17\n\x0fis_preview_flag\x18\x05 \x01(\x08\x12\x16\n\x0ein_filter_size\x18\x06 \x01(\x05\"\xb4\x01\n\rWienerRequest\x12\x13\n\x0bin_img_path\x18\x01 \x01(\t\x12\x18\n\x10process_all_flag\x18\x02 \x01(\x08\x12\x13\n\x0bin_img_list\x18\x03 \x03(\t\x12\x14\n\x0cout_img_path\x18\x04 \x01(\t\x12\x17\n\x0fis_preview_flag\x18\x05 \x01(\x08\x12\x16\n\x0ein_filter_size\x18\x06 \x01(\x05\x12\x18\n\x10wiener_power_val\x18\x07 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'denoise_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVERAGINGREQUEST']._serialized_start=18
  _globals['_AVERAGINGREQUEST']._serialized_end=175
  _globals['_GAUSSIANSMOOTHINGREQUEST']._serialized_start=178
  _globals['_GAUSSIANSMOOTHINGREQUEST']._serialized_end=343
  _globals['_BILATERALFILTERINGREQUEST']._serialized_start=346
  _globals['_BILATERALFILTERINGREQUEST']._serialized_end=540
  _globals['_MEDIANFILTERINGREQUEST']._serialized_start=543
  _globals['_MEDIANFILTERINGREQUEST']._serialized_end=706
  _globals['_WIENERREQUEST']._serialized_start=709
  _globals['_WIENERREQUEST']._serialized_end=889
# @@protoc_insertion_point(module_scope)
