# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import channel_pb2 as channel__pb2
import job_pb2 as job__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in main_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageProcessingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Channel = channel.unary_stream(
                '/grpc_ips.ImageProcessingService/Channel',
                request_serializer=channel__pb2.ChannelRequest.SerializeToString,
                response_deserializer=channel__pb2.ImageProcessingResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/grpc_ips.ImageProcessingService/GetJobStatus',
                request_serializer=job__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=job__pb2.JobStatusResponse.FromString,
                _registered_method=True)


class ImageProcessingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Channel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Channel': grpc.unary_stream_rpc_method_handler(
                    servicer.Channel,
                    request_deserializer=channel__pb2.ChannelRequest.FromString,
                    response_serializer=channel__pb2.ImageProcessingResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=job__pb2.JobStatusRequest.FromString,
                    response_serializer=job__pb2.JobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_ips.ImageProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_ips.ImageProcessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageProcessingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Channel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc_ips.ImageProcessingService/Channel',
            channel__pb2.ChannelRequest.SerializeToString,
            channel__pb2.ImageProcessingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_ips.ImageProcessingService/GetJobStatus',
            job__pb2.JobStatusRequest.SerializeToString,
            job__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
