# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import channel_pb2 as channel__pb2
import job_pb2 as job__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in main_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageProcessingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GrayscaleFilter = channel.unary_unary(
                '/vtpl_grpc_server.ImageProcessing/GrayscaleFilter',
                request_serializer=channel__pb2.GrayScaleRequest.SerializeToString,
                response_deserializer=job__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.ColorSwitchFilter = channel.unary_unary(
                '/vtpl_grpc_server.ImageProcessing/ColorSwitchFilter',
                request_serializer=channel__pb2.ColorSwitchRequest.SerializeToString,
                response_deserializer=job__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.ColorConversionFilter = channel.unary_unary(
                '/vtpl_grpc_server.ImageProcessing/ColorConversionFilter',
                request_serializer=channel__pb2.ColorConversionRequest.SerializeToString,
                response_deserializer=job__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.ExtractSingleChannelFilter = channel.unary_unary(
                '/vtpl_grpc_server.ImageProcessing/ExtractSingleChannelFilter',
                request_serializer=channel__pb2.ExtractSingleChannelRequest.SerializeToString,
                response_deserializer=job__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.DisplaySelectedChannelFilter = channel.unary_unary(
                '/vtpl_grpc_server.ImageProcessing/DisplaySelectedChannelFilter',
                request_serializer=channel__pb2.DisplaySlectedChannelRequest.SerializeToString,
                response_deserializer=job__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/vtpl_grpc_server.ImageProcessing/GetJobStatus',
                request_serializer=job__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=job__pb2.JobStatusResponse.FromString,
                _registered_method=True)


class ImageProcessingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GrayscaleFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ColorSwitchFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ColorConversionFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractSingleChannelFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplaySelectedChannelFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcessingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GrayscaleFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.GrayscaleFilter,
                    request_deserializer=channel__pb2.GrayScaleRequest.FromString,
                    response_serializer=job__pb2.JobStatusResponse.SerializeToString,
            ),
            'ColorSwitchFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.ColorSwitchFilter,
                    request_deserializer=channel__pb2.ColorSwitchRequest.FromString,
                    response_serializer=job__pb2.JobStatusResponse.SerializeToString,
            ),
            'ColorConversionFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.ColorConversionFilter,
                    request_deserializer=channel__pb2.ColorConversionRequest.FromString,
                    response_serializer=job__pb2.JobStatusResponse.SerializeToString,
            ),
            'ExtractSingleChannelFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractSingleChannelFilter,
                    request_deserializer=channel__pb2.ExtractSingleChannelRequest.FromString,
                    response_serializer=job__pb2.JobStatusResponse.SerializeToString,
            ),
            'DisplaySelectedChannelFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplaySelectedChannelFilter,
                    request_deserializer=channel__pb2.DisplaySlectedChannelRequest.FromString,
                    response_serializer=job__pb2.JobStatusResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=job__pb2.JobStatusRequest.FromString,
                    response_serializer=job__pb2.JobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vtpl_grpc_server.ImageProcessing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vtpl_grpc_server.ImageProcessing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageProcessing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GrayscaleFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vtpl_grpc_server.ImageProcessing/GrayscaleFilter',
            channel__pb2.GrayScaleRequest.SerializeToString,
            job__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ColorSwitchFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vtpl_grpc_server.ImageProcessing/ColorSwitchFilter',
            channel__pb2.ColorSwitchRequest.SerializeToString,
            job__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ColorConversionFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vtpl_grpc_server.ImageProcessing/ColorConversionFilter',
            channel__pb2.ColorConversionRequest.SerializeToString,
            job__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractSingleChannelFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vtpl_grpc_server.ImageProcessing/ExtractSingleChannelFilter',
            channel__pb2.ExtractSingleChannelRequest.SerializeToString,
            job__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplaySelectedChannelFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vtpl_grpc_server.ImageProcessing/DisplaySelectedChannelFilter',
            channel__pb2.DisplaySlectedChannelRequest.SerializeToString,
            job__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vtpl_grpc_server.ImageProcessing/GetJobStatus',
            job__pb2.JobStatusRequest.SerializeToString,
            job__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
