# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: measure.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'measure.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmeasure.proto\"#\n\x0b\x43oordinates\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"0\n\x10\x43oordinatesGroup\x12\x1c\n\x06points\x18\x01 \x03(\x0b\x32\x0c.Coordinates\"\x82\x02\n\x12MeasureOneDRequest\x12\x13\n\x0bin_img_path\x18\x01 \x01(\t\x12\x18\n\x10process_all_flag\x18\x02 \x01(\x08\x12\x13\n\x0bin_img_list\x18\x03 \x03(\t\x12\x14\n\x0cout_img_path\x18\x04 \x01(\t\x12\x17\n\x0fis_preview_flag\x18\x05 \x01(\x08\x12\x31\n\x16in_ref_dual_pt_rc_list\x18\x06 \x01(\x0b\x32\x11.CoordinatesGroup\x12\x32\n\x17in_calc_dual_pt_rc_list\x18\x07 \x01(\x0b\x32\x11.CoordinatesGroup\x12\x12\n\nin_ref_val\x18\x08 \x01(\x05\"B\n\x12MeasureTwoDRequest\x12,\n\x11\x63oordinates_group\x18\x01 \x03(\x0b\x32\x11.CoordinatesGroup\"&\n\x14MeasureThreeDRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\xa9\x02\n\x0fMeasureResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\npercentage\x18\x02 \x01(\x01\x12\x18\n\x10input_image_path\x18\x03 \x01(\t\x12\x19\n\x11output_image_path\x18\x04 \x01(\t\x12\x1a\n\x12total_input_images\x18\x05 \x01(\x03\x12\x1d\n\x15processed_image_count\x18\x06 \x01(\x03\x12\x16\n\x0estatus_message\x18\x07 \x01(\t\x12\x11\n\tcompleted\x18\x08 \x01(\x08\x12\x15\n\rerror_message\x18\t \x01(\t\x12\x14\n\x0cprocess_type\x18\n \x01(\t\x12\x13\n\x0bstatus_code\x18\x0b \x01(\x05\x12\x15\n\robject_length\x18\x0c \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'measure_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COORDINATES']._serialized_start=17
  _globals['_COORDINATES']._serialized_end=52
  _globals['_COORDINATESGROUP']._serialized_start=54
  _globals['_COORDINATESGROUP']._serialized_end=102
  _globals['_MEASUREONEDREQUEST']._serialized_start=105
  _globals['_MEASUREONEDREQUEST']._serialized_end=363
  _globals['_MEASURETWODREQUEST']._serialized_start=365
  _globals['_MEASURETWODREQUEST']._serialized_end=431
  _globals['_MEASURETHREEDREQUEST']._serialized_start=433
  _globals['_MEASURETHREEDREQUEST']._serialized_end=471
  _globals['_MEASURERESPONSE']._serialized_start=474
  _globals['_MEASURERESPONSE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
