# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdf_generate.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pdf_generate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pdf_generate.proto\"g\n\nExeDetails\x12)\n\x07\x64\x65tails\x18\x01 \x03(\x0b\x32\x18.ExeDetails.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"x\n\x07Process\x12\x15\n\rprocess_index\x18\x01 \x01(\x05\x12\x14\n\x0cprocess_name\x18\x02 \x01(\t\x12\x1e\n\x16\x65xe_details_avail_flag\x18\x03 \x01(\x08\x12 \n\x0b\x65xe_details\x18\x04 \x01(\x0b\x32\x0b.ExeDetails\"5\n\x0bProcessMeta\x12&\n\x1einput_output_image_show_report\x18\x01 \x01(\x08\"n\n\x12PDFGenerateRequest\x12\x1b\n\tprocesses\x18\x01 \x03(\x0b\x32\x08.Process\x12$\n\x0eprocesses_meta\x18\x02 \x01(\x0b\x32\x0c.ProcessMeta\x12\x15\n\rout_docs_path\x18\x03 \x01(\t\"j\n\x13PDFGenerateResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\x12\x0f\n\x07pdf_url\x18\x03 \x01(\t\x12\x15\n\rerror_details\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pdf_generate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXEDETAILS_DETAILSENTRY']._loaded_options = None
  _globals['_EXEDETAILS_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_EXEDETAILS']._serialized_start=22
  _globals['_EXEDETAILS']._serialized_end=125
  _globals['_EXEDETAILS_DETAILSENTRY']._serialized_start=79
  _globals['_EXEDETAILS_DETAILSENTRY']._serialized_end=125
  _globals['_PROCESS']._serialized_start=127
  _globals['_PROCESS']._serialized_end=247
  _globals['_PROCESSMETA']._serialized_start=249
  _globals['_PROCESSMETA']._serialized_end=302
  _globals['_PDFGENERATEREQUEST']._serialized_start=304
  _globals['_PDFGENERATEREQUEST']._serialized_end=414
  _globals['_PDFGENERATERESPONSE']._serialized_start=416
  _globals['_PDFGENERATERESPONSE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
