name: GitHub Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/config.ovpn
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}
          client_key: ${{ secrets.USER_KEY }}

      - name: Force reset Git user info
        run: |
          git config --global --unset user.email || true
          git config --global --unset user.name || true
          git config --global user.email "abhishek.udiya@videonetics.com"
          git config --global user.name "Abhishek"
          git config --list  # Check the applied Git settings

      - name: Use SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x .github/workflows/deply.sh  # Correct path to the script
            ./.github/workflows/deply.sh           # Correctly reference the script's path
