name: CI/CD Pipeline

on:
  push:
    branches:
      - updating-with-two-rpc
  pull_request:
    branches:
      - updating-with-two-rpc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7  # Updated version
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/vadmin/python-grpc-server/vtpl-grpc-server
            git fetch origin
            git reset --hard origin/updating-with-two-rpc  # Ensures latest changes
            pip install --upgrade -r requirements.txt  # Upgrade dependencies
            systemctl restart myproject.service  # Restart service
          debug: true  # Keep this for debugging purposes
